name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: kaizensnsilvam
  REGION: us-central1
  SERVICE: kaizensnsilvam-frontend
  IMAGE: kaizensnsilvam-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # 🔑 OIDC obligatorio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Authenticate to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/778334880592/locations/global/workloadIdentityPools/github-pool/providers/github-frontend-provider
          service_account: github-actions-frontend@kaizensnsilvam.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_SEBAS_KEY: ${{ secrets.VITE_SEBAS_KEY }}
          VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID }}
        run: |
          docker build \
            --build-arg "VITE_API_URL=$VITE_API_URL" \
            --build-arg "VITE_SEBAS_KEY=$VITE_SEBAS_KEY" \
            --build-arg "VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY" \
            --build-arg "VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN" \
            --build-arg "VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID" \
            --build-arg "VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID" \
            -t us-central1-docker.pkg.dev/kaizensnsilvam/frontend/kaizensnsilvam-frontend:latest .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/kaizensnsilvam/frontend/kaizensnsilvam-frontend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy kaizensnsilvam-frontend \
            --image us-central1-docker.pkg.dev/kaizensnsilvam/frontend/kaizensnsilvam-frontend:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port 8080
